// GENERATED by build-tokens.mjs from tokens.json — do not edit by hand.
import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

/// Cosmique design tokens, shared with the web design system.
public enum Cosmique {

    // MARK: Colour
    public enum Color {
    public static let paper = dynamic(light: 0xEBE6D7, dark: 0x141312)
    public static let card = dynamic(light: 0xEFEBDD, dark: 0x1B1A17)
    public static let ink = dynamic(light: 0x26231C, dark: 0xE9E3D4)
    public static let muted = dynamic(light: 0x857F6E, dark: 0x8C8677)
    public static let hair = dynamic(light: 0xD6D0BE, dark: 0x302C26)
    public static let accent = dynamic(light: 0xBC4630, dark: 0xD2502F)
    public static let sage = dynamic(light: 0x9FA48E, dark: 0x9FA48E)
    public static let positive = dynamic(light: 0x5E7D4F, dark: 0x84A86E)
    public static let negative = dynamic(light: 0xB23B2C, dark: 0xD2502F)
    public static let warning = dynamic(light: 0xC28A2B, dark: 0xD9A441)
    public static let info = dynamic(light: 0x4A6275, dark: 0x7E97A8)

        /// A colour that resolves light/dark automatically on iOS,
        /// and falls back to the light value elsewhere.
        static func dynamic(light: UInt, dark: UInt) -> SwiftUI.Color {
            #if canImport(UIKit)
            return SwiftUI.Color(UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(rgb: dark) : UIColor(rgb: light)
            })
            #else
            return SwiftUI.Color(rgb: light)
            #endif
        }
    }

    // MARK: Type scale (pt)
    public enum Size {
    public static let h1: CGFloat = 52
    public static let h2: CGFloat = 26
    public static let h3: CGFloat = 20
    public static let body: CGFloat = 16
    public static let small: CGFloat = 13
    public static let kicker: CGFloat = 11
    }

    // MARK: Spacing scale (pt)
    public enum Space {
    public static let xs: CGFloat = 8
    public static let sm: CGFloat = 14
    public static let md: CGFloat = 24
    public static let lg: CGFloat = 40
    public static let xl: CGFloat = 64
    public static let xxl: CGFloat = 96
    }

    // MARK: Corner radius (pt)
    public enum Radius {
    public static let sm: CGFloat = 2
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 16
    }
}

// MARK: - Hex helpers
extension SwiftUI.Color {
    init(rgb: UInt) {
        self.init(
            .sRGB,
            red:   Double((rgb >> 16) & 0xFF) / 255,
            green: Double((rgb >> 8) & 0xFF) / 255,
            blue:  Double(rgb & 0xFF) / 255,
            opacity: 1
        )
    }
}
#if canImport(UIKit)
extension UIColor {
    convenience init(rgb: UInt) {
        self.init(
            red:   CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue:  CGFloat(rgb & 0xFF) / 255,
            alpha: 1
        )
    }
}
#endif
