#!/usr/bin/env node
/**
 * Cosmique token generator — zero dependencies.
 *
 *   node build-tokens.mjs
 *
 * Reads tokens.json (the source of truth) and writes:
 *   - css/tokens.css      CSS custom properties, with [data-theme="dark"] overrides
 *   - swift/Tokens.swift  SwiftUI palette (dynamic light/dark) + scale constants
 *
 * If you outgrow this, the token structure maps onto Style Dictionary directly:
 * each color is a token with `light`/`dark` modes; sizes/space/radius are dimensions.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));

/* ----------------------------------------------------------- CSS ---------- */
const colorLight = [];
const colorDark = [];
const other = [];

for (const [name, v] of Object.entries(t.color)) {
  colorLight.push(`  --color-${name}: ${v.light};`);
  if (v.dark && v.dark !== v.light) colorDark.push(`  --color-${name}: ${v.dark};`);
}
for (const [name, v] of Object.entries(t.font)) other.push(`  --font-${name}: ${v};`);
for (const [name, v] of Object.entries(t.size)) other.push(`  --size-${name}: ${v}px;`);
for (const [name, v] of Object.entries(t.weight)) other.push(`  --weight-${name}: ${v};`);
for (const [name, v] of Object.entries(t.space)) other.push(`  --space-${name}: ${v}px;`);
for (const [name, v] of Object.entries(t.radius)) other.push(`  --radius-${name}: ${v}px;`);
for (const [name, v] of Object.entries(t.tracking)) other.push(`  --tracking-${name}: ${v};`);

const css =
`/* GENERATED by build-tokens.mjs from tokens.json — do not edit by hand. */
:root{
${colorLight.join("\n")}
${other.join("\n")}
}

/* Force any subtree to a theme: data-theme="light" | "dark". Defaults to light. */
[data-theme="dark"]{
${colorDark.join("\n")}
}

[data-theme="light"]{
${colorLight.join("\n")}
}
`;
mkdirSync(join(here, "css"), { recursive: true });
writeFileSync(join(here, "css/tokens.css"), css);

/* --------------------------------------------------------- SwiftUI -------- */
const hex = (h) => "0x" + h.replace("#", "").toUpperCase();
const palette = Object.entries(t.color)
  .map(([n, v]) => `    public static let ${n} = dynamic(light: ${hex(v.light)}, dark: ${hex(v.dark || v.light)})`)
  .join("\n");
const sizes = Object.entries(t.size).map(([n, v]) => `    public static let ${n}: CGFloat = ${v}`).join("\n");
const spaces = Object.entries(t.space).map(([n, v]) => `    public static let ${n}: CGFloat = ${v}`).join("\n");
const radii = Object.entries(t.radius).map(([n, v]) => `    public static let ${n}: CGFloat = ${v}`).join("\n");

const swift =
`// GENERATED by build-tokens.mjs from tokens.json — do not edit by hand.
import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

/// Cosmique design tokens, shared with the web design system.
public enum Cosmique {

    // MARK: Colour
    public enum Color {
${palette}

        /// A colour that resolves light/dark automatically on iOS,
        /// and falls back to the light value elsewhere.
        static func dynamic(light: UInt, dark: UInt) -> SwiftUI.Color {
            #if canImport(UIKit)
            return SwiftUI.Color(UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(rgb: dark) : UIColor(rgb: light)
            })
            #else
            return SwiftUI.Color(rgb: light)
            #endif
        }
    }

    // MARK: Type scale (pt)
    public enum Size {
${sizes}
    }

    // MARK: Spacing scale (pt)
    public enum Space {
${spaces}
    }

    // MARK: Corner radius (pt)
    public enum Radius {
${radii}
    }
}

// MARK: - Hex helpers
extension SwiftUI.Color {
    init(rgb: UInt) {
        self.init(
            .sRGB,
            red:   Double((rgb >> 16) & 0xFF) / 255,
            green: Double((rgb >> 8) & 0xFF) / 255,
            blue:  Double(rgb & 0xFF) / 255,
            opacity: 1
        )
    }
}
#if canImport(UIKit)
extension UIColor {
    convenience init(rgb: UInt) {
        self.init(
            red:   CGFloat((rgb >> 16) & 0xFF) / 255,
            green: CGFloat((rgb >> 8) & 0xFF) / 255,
            blue:  CGFloat(rgb & 0xFF) / 255,
            alpha: 1
        )
    }
}
#endif
`;
const swiftDir = join(here, "CosmiquePreviews/Sources/CosmiqueUI");
mkdirSync(swiftDir, { recursive: true });
writeFileSync(join(swiftDir, "Tokens.swift"), swift);

console.log("✓ wrote css/tokens.css and CosmiquePreviews/Sources/CosmiqueUI/Tokens.swift");
